package com.lumenlauncher.app.domain

import com.lumenlauncher.app.data.local.DefaultFavoriteAppEntity
import com.lumenlauncher.app.data.local.DockAppEntity
import com.lumenlauncher.app.data.local.FavoriteAppEntity
import com.lumenlauncher.app.data.local.ProfileEntity
import com.lumenlauncher.app.data.local.WidgetPlacementEntity
import com.lumenlauncher.app.data.model.AppRowPosition
import com.lumenlauncher.app.data.model.AppRowPresentation
import com.lumenlauncher.app.data.model.BackupAppEntry
import com.lumenlauncher.app.data.model.BackupProfile
import com.lumenlauncher.app.data.model.BackupWidgetPlacement
import com.lumenlauncher.app.data.model.ClockColorOption
import com.lumenlauncher.app.data.model.ClockFontOption
import com.lumenlauncher.app.data.model.ClockTemplateId
import com.lumenlauncher.app.data.model.FontWeightOption
import com.lumenlauncher.app.data.model.ListContentMode
import com.lumenlauncher.app.data.selectedCalendarIds

/** F14 Backup & Restore — entity <-> DTO mapping shared by [ExportBackupUseCase]/[ImportBackupUseCase]. Every enum round-trips through its raw name with a fallback to the field's own default, matching `Converters.kt`'s established pattern. */

fun FavoriteAppEntity.toBackupEntry(): BackupAppEntry = BackupAppEntry(packageName, activityName, position)

fun DockAppEntity.toBackupEntry(): BackupAppEntry = BackupAppEntry(packageName, activityName, position)

fun DefaultFavoriteAppEntity.toBackupEntry(): BackupAppEntry = BackupAppEntry(packageName, activityName, position)

fun BackupAppEntry.toFavoriteAppEntity(profileId: Long): FavoriteAppEntity =
    FavoriteAppEntity(profileId = profileId, packageName = packageName, activityName = activityName, position = position)

fun BackupAppEntry.toDockAppEntity(): DockAppEntity = DockAppEntity(packageName = packageName, activityName = activityName, position = position)

fun BackupAppEntry.toDefaultFavoriteAppEntity(): DefaultFavoriteAppEntity =
    DefaultFavoriteAppEntity(packageName = packageName, activityName = activityName, position = position)

fun WidgetPlacementEntity.toBackupPlacement(): BackupWidgetPlacement =
    BackupWidgetPlacement(providerPackageName, providerClassName, row, col, colSpan, rowSpan)

fun ProfileEntity.toBackupProfile(favorites: List<BackupAppEntry>): BackupProfile = BackupProfile(
    name = name,
    position = position,
    overrideClock = overrideClock,
    clockTemplateId = clockTemplateId.name,
    clockFontOption = clockFontOption.name,
    clockColorOption = clockColorOption.name,
    use24HourTime = use24HourTime,
    clockShowMeridiem = clockShowMeridiem,
    overrideApps = overrideApps,
    appRowPosition = appRowPosition.name,
    appRowPresentation = appRowPresentation.name,
    listContentMode = listContentMode.name,
    appsToShowCount = appsToShowCount,
    overridingFavorites = overridingFavorites,
    overrideCalendar = overrideCalendar,
    showAllDayEvents = showAllDayEvents,
    calendarFontOption = calendarFontOption.name,
    calendarColorOption = calendarColorOption.name,
    calendarFontWeight = calendarFontWeight.name,
    selectedCalendarIds = selectedCalendarIds?.toList(),
    favorites = favorites,
)

/** The restored profile's own row id is always `0` (autogenerated fresh on insert) — see `ProfileRepository.restoreProfile`. */
fun BackupProfile.toProfileEntity(): ProfileEntity = ProfileEntity(
    id = 0,
    name = name,
    position = position,
    overrideClock = overrideClock,
    clockTemplateId = clockTemplateId.toEnumOrDefault(ClockTemplateId.LIGHT_STACK),
    clockFontOption = clockFontOption.toEnumOrDefault(ClockFontOption.LAUNCHER_DEFAULT),
    clockColorOption = clockColorOption.toEnumOrDefault(ClockColorOption.THEME),
    use24HourTime = use24HourTime,
    clockShowMeridiem = clockShowMeridiem,
    overrideApps = overrideApps,
    appRowPosition = appRowPosition.toEnumOrDefault(AppRowPosition.LEFT),
    appRowPresentation = appRowPresentation.toEnumOrDefault(AppRowPresentation.ICON_AND_TEXT),
    listContentMode = listContentMode.toEnumOrDefault(ListContentMode.FAVORITES),
    appsToShowCount = appsToShowCount.coerceIn(4, 8),
    overridingFavorites = overridingFavorites,
    overrideCalendar = overrideCalendar,
    showAllDayEvents = showAllDayEvents,
    calendarFontOption = calendarFontOption.toEnumOrDefault(ClockFontOption.LAUNCHER_DEFAULT),
    calendarColorOption = calendarColorOption.toEnumOrDefault(ClockColorOption.THEME),
    calendarFontWeight = calendarFontWeight.toEnumOrDefault(FontWeightOption.REGULAR),
    selectedCalendarIdsCsv = selectedCalendarIds?.joinToString(","),
)

/** An unrecognized stored name (an old export from before an enum constant was renamed) falls back to [default] rather than failing the whole import — same contract as `Converters.kt`. */
inline fun <reified T : Enum<T>> String.toEnumOrDefault(default: T): T =
    runCatching { enumValueOf<T>(this) }.getOrDefault(default)
