package com.facetlauncher.app.data.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Bumped whenever [BackupBundle]'s shape changes — [com.facetlauncher.app.domain.ImportBackupUseCase] rejects anything newer than it understands. */
const val CURRENT_BACKUP_VERSION = 3

/**
 * The full exported/imported settings snapshot for F14 Backup & Restore (PRD: "not limited to
 * favorites/profiles/dock — also includes widget hub state... icon/label customization... and
 * other user settings. Effectively a full settings snapshot, not a partial one.").
 *
 * Every enum field throughout this file is stored as its raw `.name` string (matching this
 * codebase's existing `Converters.kt`/`SettingsRepository` convention) rather than depending on
 * `data/model` enums being `@Serializable` themselves — [com.facetlauncher.app.domain.ExportBackupUseCase]/
 * [com.facetlauncher.app.domain.ImportBackupUseCase] convert to/from the real enum with the same
 * `runCatching { Enum.valueOf(it) }.getOrNull() ?: default` fallback used everywhere else in this
 * codebase, so an unrecognized value (an old export from before an enum constant was renamed)
 * degrades to that field's default instead of failing the whole import.
 *
 * Deliberately excluded from [BackupSettings] — not oversights, see each field's own reasoning:
 * - `activeFacetId`: a raw Room row id, meaningless after restore (facets get fresh
 *   autogenerated ids on import) — replaced by [BackupSettings.activeFacetIndex], an index into
 *   [BackupBundle.facets] that [com.facetlauncher.app.domain.ImportBackupUseCase] resolves to
 *   the newly-created facet's real id.
 * - `selectedCalendarIds`/`calendarColors`: keyed by `CalendarContract.Calendars` row ids, which
 *   are local-`ContentProvider` autoincrement values tied to which calendar accounts are synced
 *   on *this* device in *this* order — not portable to another device/reinstall, and silently
 *   matching the wrong calendar by coincidence is worse than just re-deriving them fresh.
 * - `calendarPermissionRequested`/`contactsPermissionRequested`: track *this install's* runtime
 *   permission-request history, not a user preference — restoring `true` onto a device that was
 *   never actually asked would wrongly skip straight to the "go to App Info" fallback instead of
 *   firing the real system permission dialog.
 * - `onboardingCompleted`/`defaultsSeeded`/`coachMarksSeen`: this install's own first-run
 *   progress, not a user preference — restoring `true`/a populated set onto a fresh install would
 *   skip the first-run flow and its dock-seeding/coach-mark introductions entirely.
 */
@Serializable
data class BackupBundle(
    val backupVersion: Int = CURRENT_BACKUP_VERSION,
    val exportedAtEpochMillis: Long,
    val settings: BackupSettings,
    /** `@SerialName` keeps the JSON key `"profiles"` so backups exported before the Facet rename still import. */
    @SerialName("profiles")
    val facets: List<BackupFacet>,
    val dockApps: List<BackupAppEntry>,
    val defaultFavoriteApps: List<BackupAppEntry>,
    val widgetPlacements: List<BackupWidgetPlacement>,
    /**
     * The whole folder library (F-Folders) — every folder, regardless of where (if anywhere) it's
     * placed, in no particular order. Referenced by index (not id — a folder's own row id isn't
     * portable, same reasoning as [BackupSettings.activeFacetIndex]) from [dockFolderPlacements],
     * [defaultFavoriteFolderPlacements], and each [BackupFacet]'s own placement lists. Defaulted —
     * tolerant-reader discipline, see this file's own doc comment (a pre-Folders backup still
     * deserializes cleanly, with no folders to restore).
     */
    val folders: List<BackupFolder> = emptyList(),
    /** A folder placed in the launcher-wide default Dock — mirrors [dockApps] on the folder side. */
    val dockFolderPlacements: List<BackupFolderPlacement> = emptyList(),
    /** A folder placed in the launcher-wide default Favorites list — mirrors [defaultFavoriteApps] on the folder side. */
    val defaultFavoriteFolderPlacements: List<BackupFolderPlacement> = emptyList(),
)

@Serializable
data class BackupSettings(
    val use24HourTime: Boolean,
    val dockDisplayMode: String,
    val drawerPresentation: String,
    val drawerGridSize: String,
    val drawerListItemSize: String,
    val drawerOpacity: Float,
    val notificationDotsEnabled: Boolean,
    val notificationBadgeStyle: String,
    val showDrawerIcons: Boolean,
    val showDrawerLabels: Boolean,
    val searchBarPosition: String,
    /**
     * See this file's own doc comment — an index into [BackupBundle.facets], not a raw id. `null` if none was active.
     * `@SerialName` keeps the JSON key `"activeProfileIndex"` so backups exported before the Facet rename still import.
     */
    @SerialName("activeProfileIndex")
    val activeFacetIndex: Int?,
    val showAllDayEvents: Boolean,
    val searchContactsEnabled: Boolean,
    val themeMode: String,
    val accentFromSystem: Boolean,
    val customAccentSwatch: String?,
    val wallpaperAccentRole: String,
    val iconRenderMode: String,
    val launcherFontOption: String,
    val appLabelColorOption: String,
    val appRowPosition: String,
    val appRowPresentation: String,
    val listContentMode: String,
    val appsToShowCount: Int,
    val clockTemplateId: String,
    val clockFontOption: String,
    val clockColorOption: String,
    val clockShowMeridiem: Boolean,
    val calendarFontOption: String,
    val calendarColorOption: String,
    /** Defaulted — tolerant-reader discipline, see this file's own doc comment (a backup from before this field existed still deserializes cleanly). */
    val calendarFontWeight: String = FontWeightOption.REGULAR.name,
    val homeAppsFontWeight: String = FontWeightOption.REGULAR.name,
)

/** Mirrors every non-id field of `FacetEntity` — its own row id isn't portable, same reasoning as [BackupSettings.activeFacetIndex]. */
@Serializable
data class BackupFacet(
    val name: String,
    val position: Int,
    val overrideClock: Boolean,
    val clockTemplateId: String,
    val clockFontOption: String,
    val clockColorOption: String,
    val use24HourTime: Boolean,
    val clockShowMeridiem: Boolean,
    val overrideApps: Boolean,
    val appRowPosition: String,
    val appRowPresentation: String,
    val listContentMode: String,
    val appsToShowCount: Int,
    val overridingFavorites: Boolean,
    /** Defaulted — tolerant-reader discipline, see this file's own doc comment (a v1 backup from before per-facet dock existed still deserializes cleanly, inheriting the launcher-wide dock). */
    val overrideDock: Boolean = false,
    val dockDisplayMode: String = DockDisplayMode.ICONS.name,
    /** This facet's own dock — only meaningful when [overrideDock], but exported unconditionally for simplicity; restoring is harmless either way since the launcher-wide dock governs whenever it isn't. */
    val dockApps: List<BackupAppEntry> = emptyList(),
    val overrideCalendar: Boolean,
    val showAllDayEvents: Boolean,
    val calendarFontOption: String,
    val calendarColorOption: String,
    /** Defaulted — tolerant-reader discipline, see this file's own doc comment. */
    val calendarFontWeight: String = FontWeightOption.REGULAR.name,
    /**
     * `null` means every calendar is implicitly selected — see [com.facetlauncher.app.data.local.FacetEntity.selectedCalendarIdsCsv]'s
     * own doc comment. A real JSON array here (not the Room column's comma-joined encoding),
     * matching how [BackupBundle] generally favors the more portable/readable shape. Defaulted
     * (not required) so an older backup missing this field still deserializes cleanly — see
     * [CURRENT_BACKUP_VERSION]'s own tolerant-reader discipline.
     */
    val selectedCalendarIds: List<String>? = null,
    /** This facet's own favorites — only meaningful when [overridingFavorites], but exported unconditionally for simplicity; restoring is harmless either way since the global default list governs whenever it isn't. */
    val favorites: List<BackupAppEntry>,
    /** A folder placed in this facet's own Dock — only meaningful when [overrideDock], mirrors [dockApps] on the folder side. Defaulted — tolerant-reader discipline. */
    val dockFolderPlacements: List<BackupFolderPlacement> = emptyList(),
    /** A folder placed in this facet's own Favorites list — only meaningful when [overridingFavorites], mirrors [favorites] on the folder side. Defaulted — tolerant-reader discipline. */
    val favoriteFolderPlacements: List<BackupFolderPlacement> = emptyList(),
)

/** A single app-list entry — dock, default favorites, or one facet's own favorites. */
@Serializable
data class BackupAppEntry(
    val packageName: String,
    val activityName: String,
    val position: Int,
)

/** One folder's identity + membership — a global, independent entity (F-Folders); see [BackupBundle.folders]' own doc for how it's referenced by index from every placement list. */
@Serializable
data class BackupFolder(
    val name: String,
    val apps: List<BackupAppEntry>,
)

/** A folder occupying one slot in some Dock/Favorites list. [folderIndex] indexes into [BackupBundle.folders] — not a raw id, same reasoning as [BackupSettings.activeFacetIndex]. */
@Serializable
data class BackupFolderPlacement(
    val folderIndex: Int,
    val position: Int,
)

/**
 * A Hub widget's *intent*, not its binding — see this file's top doc comment and the PRD's own
 * "Not yet addressed" note: an `AppWidgetHost`-issued `appWidgetId` isn't portable across installs
 * or devices, so this deliberately omits it. [com.facetlauncher.app.domain.ImportBackupUseCase]
 * never writes these to `widget_placements` directly — they're surfaced to the user as a guided
 * re-add queue (`ui/settings/backup/WidgetReimportScreen.kt`) that goes through the real
 * allocate/bind/configure flow again per widget, using [row]/[col]/[colSpan]/[rowSpan] as the
 * preferred placement.
 */
@Serializable
data class BackupWidgetPlacement(
    val providerPackageName: String,
    val providerClassName: String,
    val row: Int,
    val col: Int,
    val colSpan: Int,
    val rowSpan: Int,
)
