#!/usr/bin/env python3
"""Regenerates docs/architecture/TEST_REGISTRY.md from the test source sets.

Run after adding, renaming, or deleting any test:  python3 scripts/gen-test-registry.py
The output is committed; CI-free by design — the diff is the review.
"""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAIN = ROOT / "app/src/main/kotlin/com/facetlauncher/app"
TIERS = {
    "unit": ROOT / "app/src/test/kotlin/com/facetlauncher/app",
    "instrumented": ROOT / "app/src/androidTest/kotlin/com/facetlauncher/app",
}
OUT = ROOT / "docs/architecture/TEST_REGISTRY.md"

TEST_FUN = re.compile(r"@Test\b[^\n]*\n(?:\s*@\w+(?:\([^)]*\))?\s*\n)*\s*fun\s+(?:`([^`]+)`|(\w+))\s*\(")


def main_subject(test_class: str) -> str | None:
    """Best-effort path of the class under test, mirrored from the test's package."""
    subject = re.sub(r"Test$", "", test_class)
    hits = sorted(MAIN.rglob(f"{subject}.kt"))
    return str(hits[0].relative_to(ROOT)) if hits else None


def scan(tier: str, root: Path):
    rows = []
    for f in sorted(root.rglob("*.kt")):
        text = f.read_text()
        names = [a or b for a, b in TEST_FUN.findall(text)]
        if not names:
            continue
        pkg = str(f.parent.relative_to(root)) or "."
        harness = []
        if "RobolectricTestRunner" in text:
            harness.append("Robolectric")
        if "createComposeRule" in text or "createAndroidComposeRule" in text:
            harness.append("ComposeRule")
        if "MigrationTestHelper" in text:
            harness.append("MigrationTestHelper")
        if "runTest" in text:
            harness.append("runTest")
        rows.append(dict(tier=tier, pkg=pkg, cls=f.stem, file=str(f.relative_to(ROOT)),
                         subject=main_subject(f.stem), harness=harness, names=names))
    return rows


def render(rows):
    by_tier = defaultdict(list)
    for r in rows:
        by_tier[r["tier"]].append(r)
    total = sum(len(r["names"]) for r in rows)
    out = ["# Test Case Registry", "",
           "_Generated by `scripts/gen-test-registry.py` — do not edit by hand. Regenerate whenever a test is added, renamed, or removed._", "",
           f"**{len(rows)} test classes, {total} test cases.** "
           f"Unit: {sum(len(r['names']) for r in by_tier['unit'])} cases in {len(by_tier['unit'])} classes · "
           f"Instrumented: {sum(len(r['names']) for r in by_tier['instrumented'])} cases in {len(by_tier['instrumented'])} classes.",
           "",
           "How to read: one section per tier, one table per package (mirrors `app/src/main`), one row per test class. "
           "**Subject** is the main-source file the class name mirrors (blank = the test targets a flow/route/theme rather than one class). "
           "Expand a row to see its cases — their names are the behaviour contract.", ""]
    subjects_covered = {r["subject"] for r in rows if r["subject"]}
    for tier in ("unit", "instrumented"):
        trs = by_tier[tier]
        out += [f"## {'Unit (JVM)' if tier == 'unit' else 'Instrumented (Compose UI, emulator)'} — {len(trs)} classes", ""]
        by_pkg = defaultdict(list)
        for r in trs:
            by_pkg[r["pkg"]].append(r)
        for pkg in sorted(by_pkg):
            out += [f"### `{pkg}/`", "", "| Test class | Subject | Cases | Harness |", "|---|---|---:|---|"]
            for r in by_pkg[pkg]:
                subj = f"`{r['subject']}`" if r["subject"] else ""
                out.append(f"| [{r['cls']}]({r['file']}) | {subj} | {len(r['names'])} | {', '.join(r['harness'])} |")
            out.append("")
            for r in by_pkg[pkg]:
                out += [f"<details><summary><code>{r['cls']}</code> — {len(r['names'])} cases</summary>", ""]
                out += [f"- {n}" for n in r["names"]]
                out += ["", "</details>", ""]
    # Coverage gaps: main classes with no mirrored test class
    candidates = sorted(p for p in MAIN.rglob("*.kt")
                        if re.search(r"(Repository|UseCase|ViewModel|Dao|Converters|Migrations)\.kt$", p.name))
    missing = [p for p in candidates if str(p.relative_to(ROOT)) not in subjects_covered]
    all_test_text = {r["cls"]: Path(ROOT / r["file"]).read_text() for r in rows}
    out += ["## Main-source classes with no mirrored test class", "",
            "Repositories, use cases, ViewModels, DAOs, converters and migrations that have no `<Name>Test` in either tier. "
            "**Exercised by** lists other test classes that reference the type (indirect coverage, e.g. a DAO through its repository test, "
            "`Migrations` through `FacetDatabaseMigrationTest`); a class with nothing in that column is a real gap.", "",
            "| Class | Exercised by |", "|---|---|"]
    for p in missing:
        refs = sorted(cls for cls, txt in all_test_text.items() if re.search(rf"\b{re.escape(p.stem)}\b", txt))
        out.append(f"| `{p.relative_to(MAIN)}` | {', '.join(refs) if refs else '**none**'} |")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    rows = [r for tier, root in TIERS.items() for r in scan(tier, root)]
    OUT.write_text(render(rows))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} classes, {sum(len(r['names']) for r in rows)} cases")
